<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> {{ config.title }} | {% if page.title %} {{ page.title }} {% else %} {{ config.subtitle }} {% endif %} </title>
    <meta name="description" content="{{ config.description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="HhV5rTmhX1kf5DWeoQx-s3hNmITH4MwwmOzkETbmv0E" />

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/css/styles.css" type="text/css">

    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.0.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </head>
